import logging
from datetime import date
from typing import List, Optional

import markdown as md
from huggingface_hub import InferenceClient

from app.config import config
from app.database.models import ArticleRecord, UserProfile

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{subject}</title>
<style>
  body {{ margin: 0; padding: 0; background: #f4f6f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; }}
  .header {{ background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%); padding: 40px 32px; text-align: center; }}
  .header h1 {{ margin: 0; color: #fff; font-size: 26px; letter-spacing: 0.5px; }}
  .header p {{ margin: 8px 0 0; color: #a8b2d8; font-size: 14px; }}
  .container {{ max-width: 680px; margin: 0 auto; padding: 24px 16px; }}
  .section {{ background: #fff; border-radius: 12px; padding: 28px; margin-bottom: 20px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }}
  .section h2 {{ margin: 0 0 16px; font-size: 18px; color: #302b63; border-bottom: 2px solid #f0f0f5; padding-bottom: 10px; }}
  .section h3 {{ font-size: 15px; margin: 16px 0 4px; color: #1a1a2e; }}
  .section p {{ font-size: 14px; line-height: 1.7; margin: 4px 0 12px; color: #444; }}
  .section a {{ color: #302b63; }}
  .section ul {{ padding-left: 20px; font-size: 14px; line-height: 1.8; color: #444; }}
  .tag {{ display: inline-block; background: #f0f0f8; color: #302b63; font-size: 11px; padding: 2px 8px; border-radius: 20px; margin-bottom: 8px; }}
  .footer {{ text-align: center; font-size: 12px; color: #999; padding: 16px; }}
</style>
</head>
<body>
<div class="header">
  <h1>🤖 AI News Digest</h1>
  <p>{date_str} &nbsp;·&nbsp; {stats}</p>
</div>
<div class="container">
{sections_html}
<div class="footer">Generated by your AI News Aggregator &nbsp;·&nbsp; <a href="https://github.com">Unsubscribe</a></div>
</div>
</body>
</html>"""


def _article_summary(a: ArticleRecord) -> str:
    return f"- **[{a.title}]({a.url})** ({a.source}, {a.published_at:%b %d})\n  {a.description or ''}"


class DigestAgent:
    def __init__(self, user_profile: Optional[UserProfile] = None):
        self.client = InferenceClient(api_key=config.huggingface_api_key)
        self._profile = user_profile

    @property
    def _name(self) -> str:
        return self._profile.name if self._profile and self._profile.name else config.user_name

    @property
    def _role(self) -> str:
        return self._profile.role if self._profile and self._profile.role else config.user_role

    @property
    def _interests(self) -> List[str]:
        if self._profile and self._profile.interests:
            return self._profile.interests
        return config.user_interests

    def _llm(self, prompt: str, max_tokens: int = 1200) -> str:
        try:
            resp = self.client.chat_completion(
                model=config.llm_model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            f"You are a concise AI news analyst for {self._name}, "
                            f"a {self._role}. "
                            f"Their interests: {', '.join(self._interests)}. "
                            "Be direct, specific, and practical. Use markdown formatting."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                max_tokens=max_tokens,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            logger.error("LLM call failed: %s", e)
            return ""

    def _highlights(self, articles: List[ArticleRecord]) -> str:
        if not articles:
            return "No articles available."
        bullets = "\n".join(_article_summary(a) for a in articles)
        prompt = (
            f"For each article below, write 1-2 sentences explaining why it matters to me "
            f"given my role and interests. Format: article title as heading, then 'Why this matters:' explanation.\n\n{bullets}"
        )
        return self._llm(prompt) or "\n".join(
            f"### [{a.title}]({a.url})\n{a.description or ''}" for a in articles
        )

    def _cross_source(self, clusters: List[List[ArticleRecord]]) -> str:
        if not clusters:
            return "No cross-source topics detected in this period."
        lines = []
        for cluster in clusters[:3]:
            sources = {a.source: a for a in cluster}
            topic = cluster[0].title
            bullets = "\n".join(f"- **{src}**: [{a.title}]({a.url})" for src, a in sources.items())
            lines.append(f"**Topic: {topic}**\n{bullets}")
        prompt = (
            "Analyse these topics covered by multiple sources. For each, in 2-3 sentences: "
            "what each source emphasises differently and any blind spots.\n\n"
            + "\n\n".join(lines)
        )
        return self._llm(prompt) or "\n\n".join(lines)

    def _action_items(self, articles: List[ArticleRecord]) -> str:
        if not articles:
            return "No action items this period."
        bullets = "\n".join(_article_summary(a) for a in articles)
        prompt = (
            "Based on these articles, give me 3-5 concrete, actionable takeaways. "
            "Prefix each with a priority emoji: 🔴 urgent (act today), 🟡 this week, 🟢 when you have time. "
            "Be specific — no vague advice.\n\n" + bullets
        )
        return self._llm(prompt) or "Review the highlights above for key actions."

    def _quick_mentions(self, articles: List[ArticleRecord]) -> str:
        if not articles:
            return "No additional articles this period."
        return "\n".join(f"- [{a.title}]({a.url}) — *{a.source}*" for a in articles)

    def _trends(self, articles: List[ArticleRecord]) -> str:
        if not articles:
            return "Insufficient data for trend analysis."
        titles = "\n".join(f"- {a.title} ({a.source})" for a in articles[:20])
        prompt = (
            "Looking at these headlines, identify 2-3 emerging patterns or trend signals. "
            "For each trend: name it, explain the signal in one sentence, and give a confidence level "
            "(High / Medium / Low) with a one-sentence rationale.\n\n" + titles
        )
        return self._llm(prompt) or "Continue monitoring these sources for emerging patterns."

    def _to_html_section(self, title: str, markdown_body: str) -> str:
        body_html = md.markdown(markdown_body, extensions=["extra"])
        return f'<div class="section"><h2>{title}</h2>{body_html}</div>'

    def generate_digest(self, retrieval_result: dict) -> dict:
        ranked = retrieval_result["ranked_articles"]
        cross = retrieval_result["cross_source_topics"]
        stats = retrieval_result["stats"]

        top = ranked[:5]
        rest = ranked[5:]

        logger.info("Generating digest for %d articles (user: %s)", len(ranked), self._name)

        sections = {
            "highlights": self._highlights(top),
            "cross_source": self._cross_source(cross),
            "action_items": self._action_items(top),
            "quick_mentions": self._quick_mentions(rest),
            "trends": self._trends(ranked),
        }

        sections_html = "\n".join([
            self._to_html_section("⭐ Key Highlights", sections["highlights"]),
            self._to_html_section("🔍 Cross-Source Analysis", sections["cross_source"]),
            self._to_html_section("✅ Action Items", sections["action_items"]),
            self._to_html_section("📰 Quick Mentions", sections["quick_mentions"]),
            self._to_html_section("📈 Trend Signals", sections["trends"]),
        ])

        today = date.today()
        subject = f"🤖 AI News Digest — {today:%B %d, %Y}"
        stats_str = f"{stats['total_retrieved']} articles · {stats['unique_sources']} sources"

        html = HTML_TEMPLATE.format(
            subject=subject,
            date_str=f"{today:%B %d, %Y}",
            stats=stats_str,
            sections_html=sections_html,
        )

        return {"subject": subject, "sections": sections, "html": html, "stats_str": stats_str}

    def _rebuild_html(self, subject: str, sections: dict, stats_str: str = "") -> str:
        """Rebuild the HTML email from (possibly revised) sections."""
        section_configs = [
            ("highlights",     "⭐ Key Highlights"),
            ("cross_source",   "🔍 Cross-Source Analysis"),
            ("action_items",   "✅ Action Items"),
            ("quick_mentions", "📰 Quick Mentions"),
            ("trends",         "📈 Trend Signals"),
        ]
        sections_html = "\n".join(
            self._to_html_section(title, sections.get(key, ""))
            for key, title in section_configs
            if sections.get(key)
        )
        today = date.today()
        return HTML_TEMPLATE.format(
            subject=subject,
            date_str=f"{today:%B %d, %Y}",
            stats=stats_str or "",
            sections_html=sections_html,
        )
